baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Luís Simas'
theme = 'hugo-coder'
defaultcontentlanguage = "en"

[markup.highlight]
style = "catppuccin-mocha"

[params]
  author = "Luís Simas"
  info = "Trying stuff until it works"
  description = "Luís Simas's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"

  favicon_32 = "fav/favicon-32x32.png"
  favicon_16 = "fav/favicon-16x16.png"

  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  customSCSS = ["scss/custom.scss", "scss/_variables.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/luissimas/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/lu%C3%ADs-augusto-simas-do-nascimento-966564212"

[[params.social]]
name = "RSS"
icon = "fa fa-rss-square fa-2x"
weight = 3
url = "/posts/index.xml"

[languages]
  [languages.en]
    languageCode = 'en-US'
    languageName = ":uk:"
  [[languages.en.menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts/"
  [[languages.en.menu.main]]
    name = "About"
    weight = 2
    url = "about/"

  [languages.pt-br]
    languageCode = 'pt-BR'
    languageName = ":brazil:"
  [[languages.pt-br.menu.main]]
    name = "Blog"
    weight = 1
    url  = "posts/"
  [[languages.pt-br.menu.main]]
    name = "Sobre"
    weight = 2
    url = "about/"
  [languages.pt-br.params]
    info = "Tentando até dar certo"
    description = "Site pessoal do Luís Simas"
    keywords = "blog,desenvolvedor,pessoal"
