#+title: About

I'm Luís, a software developer living in Brasil 🇧🇷. I'm very passionate about a lot of things, some of them are:

- Dabbling with unix systems (I use arch btw)
- Custom keyboards
- Text editors
- My computer environment (you can check my [[https://github.com/luissimas/dotfiles][dotfiles]] if you want)
- Developer tooling in general
- Getting better at stuff
- Learn more about linguistics and philosophy

This website is meant to be a place to share a few things, mostly through [[file:/posts][my blog posts]]. This page is mostly a resume of my professional experience and education. If you want to get in touch or discuss anything you can email me at [[mailto:luissimas@protonmail.com][luissimas@protonmail.com]].
* Professional experience
** Back-end developer, Liven Tech (2022-Present)
Liven is a software house in São Carlos, Brasil. Our clients range from startups to big companies in a variety of domains. One of the most valuable aspects of working here is the environment that encourages me to *learn constantly* and *take ownership* of the products we ship.

As a back-end developer at Liven I've worked mostly in the development of *REST APIs* in Node.js using Typescript and Clean Architecture. In the past few months I've been working a lot on *telecom platforms* in both Python and Node.js. I've also dabbled a bit with *infrastructure and application monitoring*, using mostly Prometheus and Grafana.

Furthermore, my time at the company has enriched my experience with Scrum practices, which are mostly applied in a small squad working on a project with constant change and development of requirements.

The work environment enabled me to start a *functional programming study group* with my coworkers. Together we developed an internal tool using Elixir and Phoenix LiveView. That was probably the experienced that sparkled my interest in *developing internal tools*.
** Software developer freelancer, Upwork (2023-Present)
In 2023 I started to work on a few projects sporadically as a freelancer. I felt that I needed more experience *dealing directly with clients*. Overall it's been a great experienced, I've done a few tools and migrations from services and databases. It's a very rewarding feeling to be able to *deliver value* by means of a complete project and get feedback directly from the client.
** Software developer, CATI Jr (2021-2023)
In the beginning of my graduation I've joined a *junior enterprise* focused on building software solutions for local businesses called CATI Jr. The bulk of my work consisted in the development of *REST APIs in Node.js*, which introduced me to project management, patterns, documentation and *Scum practices*.

At CATI Jr we had a recurring problem of low knowledge retention on the company. We managed to collaborate on the *improvement* of both *internal documentation* and company culture of sharing knowledge.
* Education
** Introduction to Functional Programming (2021)
I've attended to a [[https://www.utfpr.edu.br/][UTFPR]] extracurricular course open to the community in which I had the opportunity to met people from different countries and learn a lot about the foundations of *functional programming*.

During this course I’ve [[https://github.com/luissimas/analytic_tableaux][implemented]] a method of proving classical logic arguments know as Analytic Tableaux using Elixir, including a simple propositional logic parser using the Erlang libraries leex and yecc.

Besides that, I’ve [[https://youtu.be/rTL4TtpdjIE?t=1573][presented a talk]] about the basics of OCaml and the joy of working with algebraic data types and pattern matching on a statically typed language.
** Computer Science bachelor (2020-Present)
I’m currently a undergraduate student in computer science, actively engaging in extracurricular activities and *extension groups*. It’s also been a great opportunity to learn more about other areas that I’m interested in, mostly logic and mathematics.
** High School & Technical Certification (2017-2019)
I've attended to a high school that included an integrated technical course on software development. During this period I had the opportunity not only to *build solid technical foundations*, but also to engage in extracurricular activities, mostly in *cultural events*.
